# Generated by Django 5.0.2 on 2024-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_funds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='portfolio',
            field=models.ManyToManyField(default=[], related_name='portfolio', to='api.property'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(default=[], related_name='watchlist', to='api.property'),
        ),
    ]
