# Generated by Django 5.0.2 on 2024-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='ltp',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
            preserve_default=False,
        ),
    ]
