# Generated by Django 5.0.2 on 2024-03-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_property_category_property_location_property_ltp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=9876543210, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
