# Generated by Django 4.2.11 on 2024-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userprofile_phone_number_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(default='ABCDE1234F', max_length=10),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
