# Generated by Django 5.0.2 on 2024-03-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userprofile_phone_number_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='portfolio',
            field=models.ManyToManyField(blank=True, default=list, related_name='portfolio', to='api.property'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=list, related_name='watchlist', to='api.property'),
        ),
    ]
