# Generated by Django 5.0.2 on 2024-03-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userprofile_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='watch_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portfolio',
            field=models.ManyToManyField(blank=True, default=[], related_name='portfolio', to='api.property'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=[], related_name='watchlist', to='api.property'),
        ),
    ]
