# Generated by Django 5.0.3 on 2024-03-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_signup_userprofile_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(default='ABCDE1234F', max_length=10),
        ),
    ]
