# Generated by Django 5.0.2 on 2024-03-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_watch_list_alter_userprofile_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='watchlist',
        ),
    ]
