# Generated by Django 5.0.2 on 2024-03-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_userprofile_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='watch_list',
            new_name='watchlist',
        ),
    ]
