# Generated by Django 5.0.2 on 2024-03-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(default='ABCDE1234F', max_length=10),
        ),
    ]
